# Generated by Django 5.1.1 on 2024-10-13 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brgy', '0008_complaints_remove_incident_complaint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='status',
            field=models.CharField(max_length=50),
        ),
    ]
