# Generated by Django 5.1.1 on 2024-10-13 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brgy', '0011_remove_complaints_is_resolved_complaints_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Ongoing', 'Ongoing'), ('Closed', 'Closed')], default='Pending', max_length=10),
        ),
    ]
