# Generated by Django 5.1.1 on 2024-10-13 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brgy', '0005_complaint_incident_delete_complaints'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='incident_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
