# Generated by Django 5.1.1 on 2024-10-13 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brgy', '0006_complaint_incident_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='incident_details',
        ),
    ]
