# Generated by Django 5.1.1 on 2024-10-13 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brgy', '0007_remove_complaint_incident_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_filed', models.DateField(auto_now_add=True)),
                ('incident_date', models.DateField()),
                ('complaint_details', models.TextField()),
                ('incident_details', models.TextField()),
                ('status', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='incident',
            name='complaint',
        ),
        migrations.DeleteModel(
            name='Complaint',
        ),
        migrations.DeleteModel(
            name='Incident',
        ),
    ]
