# Generated by Django 5.1.1 on 2024-10-13 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brgy', '0009_alter_complaints_id_alter_complaints_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaints',
            name='status',
        ),
        migrations.AddField(
            model_name='complaints',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
