# Generated by Django 5.1.1 on 2024-10-13 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brgy', '0010_remove_complaints_status_complaints_is_resolved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaints',
            name='is_resolved',
        ),
        migrations.AddField(
            model_name='complaints',
            name='status',
            field=models.CharField(default='Open', max_length=255),
        ),
    ]
