# Generated by Django 5.1.1 on 2024-10-26 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brgy', '0015_barangay'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clearance',
            fields=[
                ('clearance_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('issued_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
