# Generated by Django 5.1.1 on 2024-11-02 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brgy', '0019_alter_clearance_clearance_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Population',
            fields=[
                ('barangay_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('population', models.IntegerField()),
            ],
        ),
    ]
