# Generated by Django 5.1.1 on 2024-12-07 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brgy', '0020_population'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('business_id', models.AutoField(primary_key=True, serialize=False)),
                ('business_name', models.CharField(max_length=255)),
                ('business_type', models.CharField(max_length=255)),
                ('permit_number', models.CharField(max_length=50, unique=True)),
                ('date_issued', models.DateField()),
            ],
        ),
    ]
