# Generated by Django 5.1.1 on 2024-12-08 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brgy', '0021_business'),
    ]

    operations = [
        migrations.RenameField(
            model_name='population',
            old_name='barangay_id',
            new_name='population_id',
        ),
    ]
